const COUNTRIES = [
  {
    code: "AU",
    name: "Australia",
    currencyCode: "AUD",
    currencySymbol: "$",
    clientFee: 29.99,
    legalTitle: "solicitor",
    courtLabel: "Federal Circuit and Family Court of Australia",
    dataResidency: "AWS Sydney",
    enabled: true,
    regionLabel: "State / Territory",
    regions: ["ACT", "NSW", "NT", "QLD", "SA", "TAS", "VIC", "WA"],
    disclaimer:
      "This platform does not constitute legal advice until you formally engage an Australian legal practitioner.",
    bannedPhrases: ["guaranteed outcome", "no-win certainty", "referral fee split"],
  },
  {
    code: "NZ",
    name: "New Zealand",
    currencyCode: "NZD",
    currencySymbol: "$",
    clientFee: 49.99,
    legalTitle: "lawyer",
    courtLabel: "Family Court / District Court",
    dataResidency: "AWS Sydney",
    enabled: true,
    regionLabel: "Region",
    regions: [
      "Auckland",
      "Bay of Plenty",
      "Canterbury",
      "Gisborne",
      "Hawke's Bay",
      "Manawatu-Whanganui",
      "Marlborough",
      "Nelson",
      "Northland",
      "Otago",
      "Southland",
      "Taranaki",
      "Tasman",
      "Waikato",
      "Wellington",
      "West Coast",
    ],
    disclaimer:
      "No legal advice is created through Kamieno until a New Zealand engagement is signed.",
    bannedPhrases: ["guaranteed outcome", "certain win"],
  },
  {
    code: "UK",
    name: "United Kingdom",
    currencyCode: "GBP",
    currencySymbol: "£",
    clientFee: 22.99,
    legalTitle: "solicitor",
    courtLabel: "Courts & Tribunals Service",
    dataResidency: "eu-west-1",
    enabled: true,
    regionLabel: "Nation",
    regions: ["England & Wales", "Scotland", "Northern Ireland"],
    disclaimer:
      "Using this platform does not amount to legal advice or a retainer under SRA rules until engagement.",
    bannedPhrases: ["guaranteed outcome", "success assured"],
  },
  {
    code: "US",
    name: "United States",
    currencyCode: "USD",
    currencySymbol: "$",
    clientFee: 29.99,
    legalTitle: "attorney",
    courtLabel: "State / Federal Court",
    dataResidency: "us-east-1",
    enabled: true,
    regionLabel: "State",
    regions: [
      "Alabama",
      "Alaska",
      "Arizona",
      "Arkansas",
      "California",
      "Colorado",
      "Connecticut",
      "Delaware",
      "District of Columbia",
      "Florida",
      "Georgia",
      "Hawaii",
      "Idaho",
      "Illinois",
      "Indiana",
      "Iowa",
      "Kansas",
      "Kentucky",
      "Louisiana",
      "Maine",
      "Maryland",
      "Massachusetts",
      "Michigan",
      "Minnesota",
      "Mississippi",
      "Missouri",
      "Montana",
      "Nebraska",
      "Nevada",
      "New Hampshire",
      "New Jersey",
      "New Mexico",
      "New York",
      "North Carolina",
      "North Dakota",
      "Ohio",
      "Oklahoma",
      "Oregon",
      "Pennsylvania",
      "Rhode Island",
      "South Carolina",
      "South Dakota",
      "Tennessee",
      "Texas",
      "Utah",
      "Vermont",
      "Virginia",
      "Washington",
      "West Virginia",
      "Wisconsin",
      "Wyoming",
    ],
    disclaimer:
      "Information on Kamieno is not legal advice and does not create an attorney-client relationship until engagement.",
    bannedPhrases: ["guaranteed outcome", "certain verdict", "win guaranteed"],
  },
  {
    code: "CA",
    name: "Canada",
    currencyCode: "CAD",
    currencySymbol: "$",
    clientFee: 39.99,
    legalTitle: "lawyer",
    courtLabel: "Provincial / Federal Court",
    dataResidency: "ca-central-ready",
    enabled: true,
    regionLabel: "Province / Territory",
    regions: [
      "Alberta",
      "British Columbia",
      "Manitoba",
      "New Brunswick",
      "Newfoundland and Labrador",
      "Northwest Territories",
      "Nova Scotia",
      "Nunavut",
      "Ontario",
      "Prince Edward Island",
      "Quebec",
      "Saskatchewan",
      "Yukon",
    ],
    disclaimer:
      "Kamieno is an introductions platform only until a Canadian retainer or engagement letter is accepted.",
    bannedPhrases: ["guaranteed outcome", "guaranteed approval"],
  },
  {
    code: "IE",
    name: "Ireland",
    currencyCode: "EUR",
    currencySymbol: "EUR ",
    clientFee: 27.99,
    legalTitle: "solicitor",
    courtLabel: "Circuit / High Court",
    dataResidency: "eu-west-1",
    enabled: true,
    regionLabel: "County",
    regions: [
      "Carlow",
      "Cavan",
      "Clare",
      "Cork",
      "Donegal",
      "Dublin",
      "Galway",
      "Kerry",
      "Kildare",
      "Kilkenny",
      "Laois",
      "Leitrim",
      "Limerick",
      "Longford",
      "Louth",
      "Mayo",
      "Meath",
      "Monaghan",
      "Offaly",
      "Roscommon",
      "Sligo",
      "Tipperary",
      "Waterford",
      "Westmeath",
      "Wexford",
      "Wicklow",
    ],
    disclaimer:
      "No Irish legal advice or formal solicitor-client relationship exists until engagement documentation is signed.",
    bannedPhrases: ["guaranteed outcome", "guaranteed approval"],
  },
];

const PRACTICE_AREAS = [
  {
    id: "family-divorce",
    label: "Family Law & Divorce",
    category: "Private client",
    prompts: ["Date of separation", "Children involved", "Property pool estimate"],
    uploads: ["Court orders", "Financial statements", "Parenting plan"],
  },
  {
    id: "child-custody",
    label: "Child Custody, Parenting & Family Disputes",
    category: "Private client",
    prompts: ["Current parenting schedule", "Safety concerns", "Schooling arrangements"],
    uploads: ["Parenting orders", "Mediation notes", "School correspondence"],
  },
  {
    id: "personal-injury",
    label: "Personal Injury & Accident Claims",
    category: "Litigation",
    prompts: ["Date of accident", "Injuries sustained", "Insurer details"],
    uploads: ["Police report", "Medical bills", "Photos of incident"],
  },
  {
    id: "medical-negligence",
    label: "Medical Negligence / Malpractice",
    category: "Litigation",
    prompts: ["Treatment dates", "Provider details", "Current harm or losses"],
    uploads: ["Medical records", "Specialist opinions", "Invoices"],
  },
  {
    id: "employment",
    label: "Employment & Workplace Disputes",
    category: "Workplace",
    prompts: ["Employment status", "Key dates", "Desired outcome"],
    uploads: ["Employment contract", "Payslips", "Warning letters"],
  },
  {
    id: "criminal-defence",
    label: "Criminal Defence",
    category: "Defence",
    prompts: ["Charge or allegation", "Next court date", "Bail status"],
    uploads: ["Charge sheet", "Police facts", "Bail paperwork"],
  },
  {
    id: "traffic",
    label: "Traffic Offences & Road Traffic Law",
    category: "Defence",
    prompts: ["Offence date", "Licence status", "Any prior offences"],
    uploads: ["Infringement notice", "Traffic history", "Dashcam footage"],
  },
  {
    id: "wills-probate",
    label: "Wills, Estates & Probate",
    category: "Private client",
    prompts: ["Executor status", "Estate size", "Any disputes anticipated"],
    uploads: ["Will copy", "Death certificate", "Asset list"],
  },
  {
    id: "estate-litigation",
    label: "Estate Litigation & Contested Wills",
    category: "Litigation",
    prompts: ["Grounds of challenge", "Relationship to deceased", "Urgent deadlines"],
    uploads: ["Will copy", "Correspondence", "Medical history records"],
  },
  {
    id: "property",
    label: "Property & Real Estate Law",
    category: "Property",
    prompts: ["Property address", "Transaction stage", "Key issue to resolve"],
    uploads: ["Contract of sale", "Title search", "Lease or tenancy document"],
  },
  {
    id: "commercial",
    label: "Business & Commercial Law",
    category: "Business",
    prompts: ["Business type", "Counterparty", "Commercial objective"],
    uploads: ["Shareholder agreement", "Term sheet", "Relevant contracts"],
  },
  {
    id: "contract-disputes",
    label: "Contract Disputes & Breaches",
    category: "Business",
    prompts: ["Contract date", "Breach alleged", "Loss suffered"],
    uploads: ["Signed contract", "Variation emails", "Demand letter"],
  },
  {
    id: "ip",
    label: "Intellectual Property",
    category: "Business",
    prompts: ["IP type", "Registration status", "Commercial risk"],
    uploads: ["Trade mark certificate", "Licence agreement", "Evidence of use"],
  },
  {
    id: "consumer",
    label: "Consumer Law & Disputes",
    category: "Private client",
    prompts: ["Product or service", "Supplier details", "Refund sought"],
    uploads: ["Receipts", "Terms and conditions", "Complaint emails"],
  },
  {
    id: "debt-insolvency",
    label: "Debt Recovery, Bankruptcy & Insolvency",
    category: "Business",
    prompts: ["Debt amount", "Debtor status", "Any security held"],
    uploads: ["Invoices", "Security documents", "Demand notices"],
  },
  {
    id: "immigration",
    label: "Immigration & Visa Law",
    category: "Migration",
    prompts: ["Visa type", "Application stage", "Urgent deadlines"],
    uploads: ["Passport", "Refusal letter", "Application receipt"],
  },
  {
    id: "retirement",
    label: "Superannuation & Retirement Law",
    category: "Private client",
    prompts: ["Fund or scheme", "Benefit issue", "Any trustee communication"],
    uploads: ["Fund statements", "Trust deed extracts", "Correspondence"],
  },
  {
    id: "tax",
    label: "Tax Law & Disputes",
    category: "Business",
    prompts: ["Tax authority", "Assessment amount", "Objection deadline"],
    uploads: ["Notice of assessment", "Working papers", "ATO/IRS/HMRC letters"],
  },
  {
    id: "construction",
    label: "Construction & Building Disputes",
    category: "Property",
    prompts: ["Project type", "Contract value", "Defects or payment issue"],
    uploads: ["Building contract", "Defect report", "Progress claims"],
  },
  {
    id: "environmental",
    label: "Environmental Law",
    category: "Regulatory",
    prompts: ["Regulator involved", "Permit or notice", "Commercial impact"],
    uploads: ["Notice from regulator", "Permit documents", "Expert reports"],
  },
  {
    id: "administrative",
    label: "Administrative & Government Law",
    category: "Regulatory",
    prompts: ["Decision-maker", "Decision date", "Review avenue sought"],
    uploads: ["Decision notice", "Internal review material", "Evidence pack"],
  },
  {
    id: "elder-law",
    label: "Elder Law & Aged Care",
    category: "Private client",
    prompts: ["Care arrangement", "Capacity concerns", "Financial issue"],
    uploads: ["Care agreement", "Power of attorney", "Medical report"],
  },
  {
    id: "neighbourhood",
    label: "Neighbourhood & Strata Disputes",
    category: "Property",
    prompts: ["Nature of dispute", "Attempts to resolve", "Body corporate involved"],
    uploads: ["Notices", "By-laws", "Photos or reports"],
  },
  {
    id: "other",
    label: "Other",
    category: "Review",
    prompts: ["Matter type", "Urgency", "Desired outcome"],
    uploads: ["Any supporting documents"],
  },
];

const TEMPLATE_OVERRIDES = {
  AU: {
    "family-divorce": {
      prompts: ["Date of separation", "Children's names and ages", "Property pool value"],
      uploads: ["Family Court documents", "Financial statements", "Parenting plans"],
      terminology: "Solicitor-led family strategy with fixed fee + disbursements + GST.",
    },
    retirement: {
      label: "Superannuation & Retirement Law",
      prompts: ["Fund name", "Binding nomination status", "Benefit dispute stage"],
    },
  },
  US: {
    "personal-injury": {
      prompts: ["Date of accident", "Injuries", "Insurance details"],
      uploads: ["Police report", "Medical bills", "Demand letter"],
      terminology: "Attorney-led claim planning with contingency fee options and statute review.",
    },
    retirement: {
      label: "Pension & Retirement Law",
      prompts: ["Plan administrator", "Benefit denied", "ERISA timeline if applicable"],
    },
  },
  UK: {
    employment: {
      prompts: ["Date of dismissal", "ACAS early conciliation reference", "Employment Tribunal deadline"],
      uploads: ["Contract", "Payslips", "ET1 form"],
      terminology: "Solicitor-led tribunal roadmap aligned to ACAS and Employment Tribunal process.",
    },
    retirement: {
      label: "Pension & Retirement Law",
      prompts: ["Scheme provider", "Pension issue", "Pensions Ombudsman stage"],
    },
  },
  CA: {
    immigration: {
      prompts: ["Visa type applied for", "IRCC file number", "Refusal or processing issue"],
      uploads: ["Refusal letter", "Passport scans", "IRCC correspondence"],
      terminology: "Lawyer strategy aligned to IRCC process and Federal Court timing.",
    },
    retirement: {
      label: "Pension & Retirement Law",
    },
  },
  NZ: {
    property: {
      prompts: ["LIM report", "Title number", "Settlement or defect concern"],
      uploads: ["Agreement for Sale & Purchase", "Building report", "Title documents"],
      terminology: "Property lawyer roadmap with LIM/title review and local conveyancing steps.",
    },
  },
};

const ROLE_COPY = {
  client: "Post once, then review tailored bids side by side.",
  lawyer: "Bid for matters only where you hold current practising rights.",
  admin: "Govern jurisdictions, verify lawyers, and watch compliance signals.",
};

function getCountry(code) {
  return COUNTRIES.find((country) => country.code === code) || COUNTRIES[0];
}

function getPracticeArea(id) {
  return PRACTICE_AREAS.find((area) => area.id === id) || PRACTICE_AREAS[0];
}

function buildTemplate(countryCode, practiceAreaId) {
  const country = getCountry(countryCode);
  const baseArea = getPracticeArea(practiceAreaId);
  const override = TEMPLATE_OVERRIDES[countryCode]?.[practiceAreaId] || {};

  return {
    areaId: baseArea.id,
    label: override.label || baseArea.label,
    category: baseArea.category,
    prompts: override.prompts || baseArea.prompts,
    uploads: override.uploads || baseArea.uploads,
    terminology:
      override.terminology ||
      `${country.legalTitle[0].toUpperCase()}${country.legalTitle.slice(1)} strategy tailored to ${country.name} procedure and pricing norms.`,
    disclaimer: country.disclaimer,
  };
}

function createSeedState() {
  return {
    settings: {
      countries: COUNTRIES.map((country) => ({ code: country.code, enabled: country.enabled })),
      launchedCountries: ["AU", "NZ", "UK"],
      futureExpansion: ["SG", "ZA"],
    },
    lawyers: [
      {
        id: "law-1",
        name: "Amelia Reid",
        email: "amelia@reidfamily.au",
        firm: "Reid Family Advisory",
        jurisdictions: ["AU:VIC", "AU:NSW"],
        certificateRefs: ["AU-VIC-44891", "AU-NSW-22170"],
        status: "verified",
      },
      {
        id: "law-2",
        name: "Joshua Carter",
        email: "joshua@bayinjury.com",
        firm: "Bay Injury Counsel",
        jurisdictions: ["US:California", "US:Nevada"],
        certificateRefs: ["CA-Bar-778210"],
        status: "verified",
      },
      {
        id: "law-3",
        name: "Harriet Singh",
        email: "harriet@tribunalnorth.co.uk",
        firm: "Tribunal North",
        jurisdictions: ["UK:England & Wales"],
        certificateRefs: ["SRA-601443"],
        status: "pending",
      },
    ],
    cases: [
      {
        id: "case-1001",
        clientName: "Olivia Brooks",
        email: "olivia@example.com",
        countryCode: "AU",
        region: "VIC",
        practiceAreaId: "family-divorce",
        quoteMode: "Detailed",
        summary: "Seeking post-separation advice about parenting arrangements and asset division.",
        budget: "Prefer staged fixed fees",
        documents: ["Minutes of consent", "Mortgage statement"],
        customAnswers: {
          "Date of separation": "2025-11-03",
          "Children's names and ages": "Two children, 8 and 11",
          "Property pool value": "Approx AUD 1.4m",
        },
        feeAmount: 29.99,
        status: "open",
        createdAt: "2026-03-14T05:45:00.000Z",
      },
      {
        id: "case-1002",
        clientName: "Marcus Lee",
        email: "marcus@example.com",
        countryCode: "UK",
        region: "England & Wales",
        practiceAreaId: "employment",
        quoteMode: "Broad",
        summary: "Dismissed after raising concerns and needs help with ACAS and tribunal timing.",
        budget: "Looking for fixed fee advice",
        documents: ["Contract", "Dismissal letter"],
        customAnswers: {
          "Date of dismissal": "2026-02-28",
          "ACAS early conciliation reference": "Pending",
          "Employment Tribunal deadline": "Unsure",
        },
        feeAmount: 22.99,
        status: "open",
        createdAt: "2026-03-14T07:10:00.000Z",
      },
    ],
    bids: [
      {
        id: "bid-9001",
        caseId: "case-1001",
        lawyerId: "law-1",
        privateBid: true,
        feeType: "Fixed fee + disbursements + GST",
        totalFee: "AUD 4,800",
        disbursements: "Court filing and valuation costs billed separately",
        sections: {
          position:
            "I would begin with an urgent review of the existing parenting and financial position, then map likely settlement ranges before any court step is taken.",
          nextSteps:
            "Within the first week I would organise disclosure, issue a concise chronology, and prepare a strategy call focused on parenting and asset preservation.",
          risks:
            "The main risk is delay around disclosure and any disagreement on interim parenting; we would keep the matter negotiation-led while preserving litigation readiness.",
          timeline:
            "Expect an initial action plan within 72 hours, negotiation windows over 3 to 6 weeks, and court-ready material if settlement stalls.",
        },
        createdAt: "2026-03-14T08:00:00.000Z",
        compliance: { safe: true, flags: [] },
      },
    ],
    decisions: {
      shortlistedBidIds: ["bid-9001"],
      acceptedBidId: null,
    },
  };
}

module.exports = {
  COUNTRIES,
  PRACTICE_AREAS,
  ROLE_COPY,
  buildTemplate,
  createSeedState,
  getCountry,
  getPracticeArea,
};
